[tool.poetry]
name = "llm-experiments"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.50.2"
langchain = "^0.3.1"
streamlit = "^1.38.0"
langchain-openai = "^0.2.1"
langchain-community = "^0.3.1"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
